<?php require VIEWS_PATH . '/includes/header.phtml'; ?>

<section class="container">
    <div class="jumbotron">
        <h2>Sobre</h2>
    </div>
    <div class="col-md-12">
        <h3>A Instituição</h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam aspernatur beatae, culpa cumque deserunt
            dolores earum excepturi facere fuga laborum minus natus necessitatibus pariatur qui quis recusandae tempore
            veniam vero.
        </p>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam aspernatur beatae, culpa cumque deserunt
            dolores earum excepturi facere fuga laborum minus natus necessitatibus pariatur qui quis recusandae tempore
            veniam vero.
        </p>
        <h3>Nossas Metas</h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam aspernatur beatae, culpa cumque deserunt
            dolores earum excepturi facere fuga laborum minus natus necessitatibus pariatur qui quis recusandae tempore
            veniam vero.
        </p>
        <h3>Valores</h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam aspernatur beatae, culpa cumque deserunt
            dolores earum excepturi facere fuga laborum minus natus necessitatibus pariatur qui quis recusandae tempore
            veniam vero.
        </p>
    </div>
</section>

<?php require VIEWS_PATH . '/includes/footer.phtml'; ?>
