<?php require VIEWS_PATH . '/includes/header.phtml';?>

    <main role="main" class="container">
        <div class="jumbotron">
            <h1>Bem vindos ao projeto de Site institucional</h1>
            <p class="lead">
                Projeto criado no curso de PHP Orientado a Objetos da Code Experts Learning.
            </p>
            <a class="btn btn-lg btn-primary" href="http://bit.ly/ce-learn" role="button">Saiba mais &raquo;</a>
        </div>
    </main>

<?php require VIEWS_PATH . '/includes/footer.phtml';?>